---
title: "Activity 03"
---

hikes <- read.csv("https://mac-stat.github.io/data/high_peaks.csv")

head(hikes)
# Excercise 4
## Adds the actual data
ggplot(hikes, aes(x = rating)) +
  geom_bar()
  
## Adds the names of the x-axis and y-axis
ggplot(hikes, aes(x = rating)) +
  geom_bar() +
  labs(x = "Rating", y = "Number of hikes")

## Changes the color of the bars to blue
ggplot(hikes, aes(x = rating)) +
  geom_bar(fill = "blue") +
  labs(x = "Rating", y = "Number of hikes")

## Changes the color of the outline of the bars
ggplot(hikes, aes(x = rating)) +
  geom_bar(color = "orange", fill = "blue") +
  labs(x = "Rating", y = "Number of hikes")
  
## removes gray outline and exchnages it with white
ggplot(hikes, aes(x = rating)) +
  geom_bar(color = "orange", fill = "blue")  +
  labs(x = "Rating", y = "Number of hikes") +
  theme_minimal()

# Excercise 5 

### The + is used to add layers to our code and make it modre tidy... labs() stands for labels and it is referring to the labels of the graph such as the x and y axis... color is essentially the border of the bars while fill is the actual bar... 'geom'is used to create a plot

